- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('ansible.builtin.env', 'HOME') }}/.ssh/id_rsa"
  pre_tasks:
    - name: update cache
      become: yes
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
      - node
      - zsh
  tasks:
    - include: dev_envi/ssh.yml
    - include: dev_envi/dotfiles.yml
    - include: dev_envi/zsh.yml
    - include: js_reqs/node.yml
    #    - debug:
    #       msg: "{{ lookup('env', 'HOME') }}"
    #    - debug:
    #       msg: "{{ lookup('env', 'USR') }}"
