- hosts: localhost
  become: true
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('ansible.builtin.env', 'HOME') }}/.ssh/id_rsa"
  pre_tasks:
    - name: update cache
      become: true
      apt:
        update_cache: true
      tags:
      - node
      - zsh
  tasks:
  - include_tasks: dev_envi/dev_envi_tasks.yml
  - include_tasks: js_reqs/js_reqs_tasks.yml
