- hosts: localhost
  become_user: root
  vars:
    source_key: "{{ hostvars[\"localhost\"][\"playbook_dir\"] }}/.ssh/id_ed25519"
    pub_key: "{{ hostvars[\"localhost\"][\"playbook_dir\"] }}/.ssh/id_ed25519.pub"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  pre_tasks:
    - name: update cache
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
      - node
      - zsh
  tasks:
    - include: debug.yml
    - include: dev_envi/decrypt.yml
    - include: dev_envi/ssh.yml
    - include: dev_envi/ssh_agent.yml
    - include: dev_envi/dotfiles.yml
    - include: dev_envi/zsh.yml
    - include: js_reqs/node.yml
