- hosts: localhost
  vars:
      source_key: "./.ssh/id_rsa"
      dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  become: true
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
      - ssh
      - node
      - zsh
  tasks:
  - include: ./ssh.yml
  - include: ./node.yml
  - include: ./zsh.yml
