- hosts: localhost
  vars:
    source_key: "{{ lookup('env', 'USER_HOME') }}/.ssh/id_ed25519"
    pub_key: "{{ lookup('env', 'USER_HOME') }}/.ssh/id_ed25519.pub"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  pre_tasks:
    - name: update cache
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
      - node
      - zsh
  tasks:
    - include: debug.yml
    - include: dev_envi/ssh.yml
    - include: dev_envi/dotfiles.yml
    - include: dev_envi/zsh.yml
    - include: js_reqs/node.yml
    #    - debug:
    #       msg: "{{ lookup('env', 'HOME') }}"
    #    - debug:
    #       msg: "{{ lookup('env', 'USR') }}"
