- hosts: localhost
  become: true
  pre_tasks:
    - name: update cache
      apt:
        update_cache: true
      tags:
      - node
      - zsh
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  tasks:
  - include: ./zsh.yml
  - include: ./node.yml
