- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:SHerlihy/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    key_file: "{{ dest_key }}"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
  - dotfiles
- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./ubuntu.sh
  tags:
    - dotfiles
