- name: Ensure .ssh directory exists.
  file:
    path: "{{ dest_key | dirname }}"
    state: directory
    mode: 0700
  tags:
  - dotfiles
  - ssh
- name: Install ssh key
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags:
  - dotfiles
  - ssh
- name: Set authorized key took from file
  authorized_key:
    user: "{{ lookup('ansible.builtin.env', 'USER') }}"
    state: present
    key: "{{ lookup('file', pub_key) }}"
  tags:
  - dotfiles
  - ssh
