- name: Ensure .ssh directory exists.
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
  - dotfiles
  - ssh
- name: Install ssh key
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags:
  - dotfiles
  - ssh
- name: Set authorized key took from file
  authorized_key:
    user: "{{ lookup('ansible.builtin.env', 'USER') }}"
    state: present
    key: "{{ lookup('ansible.builtin.env', 'HOME') }}/.ssh/id_rsa.pub"
  tags:
  - dotfiles
  - ssh
